# Generated by Django 4.2.6 on 2023-10-15 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('classification', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='musicians/')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
                ('country', models.CharField(max_length=100)),
                ('points', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('best_position', models.IntegerField()),
                ('current_position', models.IntegerField()),
                ('awards', models.ManyToManyField(related_name='musicians', to='mymusic.award')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('week', models.IntegerField()),
                ('release_year', models.PositiveSmallIntegerField()),
                ('genre', models.CharField(max_length=100)),
                ('musicians', models.ManyToManyField(related_name='songs', to='mymusic.musician')),
            ],
        ),
    ]
