# Generated by Django 5.0 on 2023-12-18 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(blank=True, max_length=20, null=True)),
                ('classification', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.CharField(max_length=100)),
                ('musician1', models.CharField(max_length=100)),
                ('points1', models.IntegerField(default=0)),
                ('musician2', models.CharField(max_length=100)),
                ('points2', models.IntegerField(default=0)),
                ('musician3', models.CharField(max_length=100)),
                ('points3', models.IntegerField(default=0)),
                ('musician4', models.CharField(max_length=100)),
                ('points4', models.IntegerField(default=0)),
                ('musician5', models.CharField(max_length=100)),
                ('points5', models.IntegerField(default=0)),
                ('musician6', models.CharField(max_length=100)),
                ('points6', models.IntegerField(default=0)),
                ('musician7', models.CharField(max_length=100)),
                ('points7', models.IntegerField(default=0)),
                ('musician8', models.CharField(max_length=100)),
                ('points8', models.IntegerField(default=0)),
                ('musician9', models.CharField(max_length=100)),
                ('points9', models.IntegerField(default=0)),
                ('musician10', models.CharField(max_length=100)),
                ('points10', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='musicians/')),
                ('flag', models.ImageField(blank=True, null=True, upload_to='flags/')),
                ('country', models.CharField(max_length=100)),
                ('points', models.IntegerField(default=0)),
                ('rating', models.IntegerField(default=0)),
                ('best_position', models.IntegerField(default=0)),
                ('current_position', models.IntegerField(default=0)),
                ('start_date_bp', models.DateField()),
                ('end_date_bp', models.DateField()),
                ('points_year', models.IntegerField(default=0)),
                ('points_semester', models.IntegerField(default=0)),
                ('awards', models.ManyToManyField(blank=True, related_name='musicians', to='mymusic.award')),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week', models.IntegerField()),
                ('position', models.IntegerField()),
                ('musician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymusic.musician')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=10)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('week', models.IntegerField(default=0)),
                ('release_year', models.PositiveSmallIntegerField(default=0)),
                ('genre', models.CharField(max_length=100)),
                ('album', models.ImageField(blank=True, null=True, upload_to='album/')),
                ('musicians', models.ManyToManyField(related_name='songs', to='mymusic.musician')),
            ],
        ),
    ]
