# Generated by Django 5.0 on 2023-12-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='end_date_bp',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='musician',
            name='start_date_bp',
            field=models.DateField(null=True),
        ),
    ]
