# Generated by Django 4.2.6 on 2023-10-17 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='best_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='musician',
            name='current_position',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='musician',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='musician',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='release_year',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='song',
            name='week',
            field=models.IntegerField(default=0),
        ),
    ]
