# Generated by Django 4.2.6 on 2023-10-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0003_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
