# Generated by Django 4.2.6 on 2023-10-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mymusic', '0004_award_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musician',
            name='awards',
            field=models.ManyToManyField(blank=True, related_name='musicians', to='mymusic.award'),
        ),
    ]
